services:
  db:
    image: mysql:8.0
    ports:
        - 3306:3306
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: service_db
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
  service:
    build: .
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
    environment:
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DB: service_db
      MYSQL_HOST: db
      MYSQL_USER: ${MYSQL_USER}
