services:
  db:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: service_db
      POSTGRES_USER: ${DB_USER}
  service:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: service_db
      DB_HOST: db
      DB_USER: ${DB_USER}
