name: Run tests

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      
      - name: Run Makefile install target for tests
        uses: make install-test

      - name: Run Makefile test target
        run: make test
